# Generated by Django 5.0.7 on 2024-09-09 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('PhoneNo', models.CharField(max_length=10)),
                ('CardNumber', models.CharField(max_length=16)),
                ('CVV', models.CharField(max_length=4)),
                ('BankName', models.CharField(default='a', max_length=100)),
                ('Address', models.CharField(default='a', max_length=100)),
                ('IFSC', models.CharField(default='a', max_length=8)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
