# Generated by Django 5.0.7 on 2024-09-10 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_billpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billpayment',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='billpayment',
            name='status',
        ),
        migrations.AddField(
            model_name='billpayment',
            name='bank',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='homepage.bank'),
            preserve_default=False,
        ),
    ]
