# Generated by Django 5.0.7 on 2024-09-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_date_billpayment_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillPayment',
        ),
    ]
