# Generated by Django 5.0.7 on 2024-09-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bills_type',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('recharge', 'Recharge'), ('dth', 'DTH'), ('rent', 'Rent'), ('water', 'Water'), ('internet', 'Internet')], max_length=100),
        ),
    ]
