# Generated by Django 5.0.7 on 2024-09-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_bills_bills_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='cardname',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
    ]
