# Generated by Django 5.0.7 on 2024-09-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_transfer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
