# Generated by Django 5.0.7 on 2024-09-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_alter_bank_cardnumber_alter_bank_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='CardNumber',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='PhoneNo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
